### ISSUE TITLE
horizontal well design 

### ISSUE THREAD

**Issue by satya5561** [fraclad/wellArchitectureDesign#1]
Hi 
can we design horizontal well using your code.
like this image.
![image](https://github.com/fraclad/wellArchitectureDesign/assets/121801/61a717e7-1bf6-4d4c-a91a-df6ff3ee3e9a)

**Comment by fraclad** [comment]
hey! 
the code doesnt allow you to create "deviated well" visuals, it only shows straight wells. in practice, we often show detailed well architecture (even for non-vertical wells) in a vertical well fashion since the general consensus is that it depicts the components and their details clearer. there are other visualization techniques that allow you to examine trajectories better. 

on a separate note, im not sure if id be able to contribute much on this project since ive succumbed to the corporate world. good luck!
